# Generated by Django 5.0.7 on 2024-07-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_three_request_times',
            field=models.JSONField(default=list),
        ),
    ]
